### ISSUE TITLE
Purrinha

### ISSUE THREAD

**Issue by RhesusP** [RRebois/ft_transcendence#28]
Les deux joueurs choisissent un nombre entre 0 et 3 x le nombre de joueurs.

Les deux joueurs choisissent un deuxieme nombre entre 0 et 6.

Lorsqu'un joueur choisi un chiffre, son choix est affiché aux autres joueurs.

En cas d'égalité, les joeurs ne gagnent pas de point.
La victoire est concédée au premier ayant 3 points.

Les parties à 4 joueurs ne sont pas des 2v2

https://github.com/RRebois/ft_transcendence/blob/BackthreeJS2nd/frontend/app/js/functions/websocket.js

**Comment by RhesusP** [comment]
### Remote game flow:
Dashboard fetch `https://localhost:8443/game/${game_type}/${code}` which returns
```
{
  code
  game
  session_id
  ws_route
}
```

Purrinha view is displayed and check if the connected user is able to play this match with a fetch to `https://localhost:8443/game/check/${game_type}/${code}` which returns the same result than the previous fetch.
Then, a websocket is initialized for the user and this websocket message is sent from backend : 
```
{
  awaited_players
  connected_players
  game
  game_state
  players
  session_id
  status
  tournament_id
  winner
}
```

When all awaited users have joined the game (`awaited_players === connected_players`), a websocket message is send to game websocket group : 
```
{
  **awaited_players: 2**
  **connected_players: 2**
  game
  game_state
  players
  session_id
  **status: "ready"**
  tournament_id
  winner
}
```

All players can asynchronously choose a number between 0 and 3. When a player choose a number, its frontend send the following websocket message : 
```
{
  action: "pick_initial_number"
  player_id
  selected_value
  session_id
  game_code
}
```

When all players have made their initial choice, backend send the following message : 
```
{
  action: "guess_sum"
  session_id
  game_code
  player: `player object guessing the sum`
  available_values: `array of available values`
}
```
> [!NOTE]  
> A value become unavailable when a user choose it.

When the current player send its sum guess, it sends :
```
{
  action: "sum_guessed"
  session_id
  game_code
  player_id: `player guessing the sum`
  selected_value: `value selected by the player`
}
```

when all players have chosen a value, backend send :
```
{
  action: "round_winner_reveal"
  session_id
  game_code
  player: `player object who wins the round`
}
```

**Comment by FelipeBelfort** [comment]
The game has been adapted to the frontend messages.

While waiting all the players for the match the back sends for each player:
```
awaited_players: int
connected_players: int
game: game name
game_state: "waiting"
players: {
username: {id: int, connected: true},
}
session_id: str
status: "waiting"
tournament_id: (always null for purrinha)
winner: str or null
```

After all players joined the match
```
awaited_players: int
connected_players: int
game: game name
game_state: {
available_to_guess: array of int 
error_message: null or str in case of an error 
history:{
username: int (won sets), username: int (won sets)
}
players:{
           player1: {name: username, quantity: bool(already chosen or not) or int(if round == "finished"), guess: int(-1 if not exists else the guess number)},
}
result: "waiting" (or the sum of the initial numbers if round == "finished")
round: "choosing" -> if all players had picked a number "guessing" -> if all actions are make "finished"
player_turn: int (the id of the player to pick a guess)
winner: "waiting" or "tie" or "username" (here is the winner of the set)
}
players: {
username: {id: int, connected: true},
}
session_id: str
status: "started"
tournament_id: (always null for purrinha)
winner: str or null (here is the winner of the whole match)
```

After each action the 'game_state' will be updated and send to all
While there is no match winner it will reset the player's data to relaunch the game

**Comment by RhesusP** [comment]
@FelipeBelfort Function that update the `player_turn` does not work as expected. Player turn is updated during the choosing round and not during the guessing round.

Please, can you update the function with the following constraints : 
- `player_turn` must not be updated is the round is not `guessing`

**Comment by RhesusP** [comment]
@FelipeBelfort I have few questions : 
1. Can you see the work I done in commit 2c16673 ? I tried to add a bot (it's only 10 lines), but I have strange behaviour while my user choose a number
2. Can you check / explain the process when a user won a round and a new round start ? I think that the `player_turn` is not updated and new actions (like `pick_initial_number` or  `sum_guessed`) are not considered by server
