### ISSUE TITLE
Router history on pong/purrinha games

### ISSUE THREAD

**Issue by tang1304** [RRebois/ft_transcendence#48]
When restarting a pong game when one is finished, it generates a new url. So it is added to the history, and if you go back, it goes to the previous /pong... url, and ends on an empty page:

![image](https://github.com/user-attachments/assets/474562a7-1308-4dc0-8681-c9eaf40f3066)
end of 2nd match

![image](https://github.com/user-attachments/assets/312d687b-de22-4f61-ba1c-c0591bc81da3)
When going back after the end of 2nd match

For the /pong and /purrinha, maybe we should add to the history once, no matter what comes next iin the url. So even if restarting x games, the previous button will bring back to the dashboard

**Comment by RhesusP** [comment]
Fixed for /pong* and /purrinha* webpages with this line :
https://github.com/RRebois/ft_transcendence/commit/3d0ca7389e33fc2471a846057789ee854f5d9087#diff-0116b0ef0f2156b20fdb7f0715f91ba35f03c77810e7cfb398733ae2f2c693e3R116
